/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SuperAdminLoginRouteImport } from './routes/super-admin-login'
import { Route as StartRouteImport } from './routes/start'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HostStandRouteImport } from './routes/host-stand'
import { Route as HealthRouteImport } from './routes/health'
import { Route as FloorplanRouteImport } from './routes/floorplan'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as BookRouteImport } from './routes/book'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlatformIndexRouteImport } from './routes/platform.index'
import { Route as PlatformRestaurantsRouteImport } from './routes/platform.restaurants'
import { Route as OnboardingStepRouteImport } from './routes/onboarding_.$step'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as CustomersIdRouteImport } from './routes/customers_.$id'
import { Route as BookSlugRouteImport } from './routes/book_.$slug'
import { Route as BillingSetupRouteImport } from './routes/billing.setup'
import { Route as BillingLockedRouteImport } from './routes/billing.locked'
import { Route as BillingCheckoutRouteImport } from './routes/billing.checkout'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AppServerRouteImport } from './routes/app_.server'
import { Route as AppReservationsRouteImport } from './routes/app_.reservations'
import { Route as AppReportsRouteImport } from './routes/app_.reports'
import { Route as AppOrdersRouteImport } from './routes/app_.orders'
import { Route as AppMenuRouteImport } from './routes/app_.menu'
import { Route as AppMarketingRouteImport } from './routes/app_.marketing'
import { Route as AppLoyaltyRouteImport } from './routes/app_.loyalty'
import { Route as AppHostRouteImport } from './routes/app_.host'
import { Route as AppGuestsRouteImport } from './routes/app_.guests'
import { Route as AppDashboardRouteImport } from './routes/app_.dashboard'
import { Route as AppAnalyticsRouteImport } from './routes/app_.analytics'
import { Route as AppGuestsIdRouteImport } from './routes/app_.guests.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminLoginRoute = SuperAdminLoginRouteImport.update({
  id: '/super-admin-login',
  path: '/super-admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HostStandRoute = HostStandRouteImport.update({
  id: '/host-stand',
  path: '/host-stand',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const FloorplanRoute = FloorplanRouteImport.update({
  id: '/floorplan',
  path: '/floorplan',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformIndexRoute = PlatformIndexRouteImport.update({
  id: '/platform/',
  path: '/platform/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRestaurantsRoute = PlatformRestaurantsRouteImport.update({
  id: '/platform/restaurants',
  path: '/platform/restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingStepRoute = OnboardingStepRouteImport.update({
  id: '/onboarding_/$step',
  path: '/onboarding/$step',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIdRoute = CustomersIdRouteImport.update({
  id: '/customers_/$id',
  path: '/customers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BookSlugRoute = BookSlugRouteImport.update({
  id: '/book_/$slug',
  path: '/book/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingSetupRoute = BillingSetupRouteImport.update({
  id: '/billing/setup',
  path: '/billing/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingLockedRoute = BillingLockedRouteImport.update({
  id: '/billing/locked',
  path: '/billing/locked',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingCheckoutRoute = BillingCheckoutRouteImport.update({
  id: '/billing/checkout',
  path: '/billing/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppServerRoute = AppServerRouteImport.update({
  id: '/app_/server',
  path: '/app/server',
  getParentRoute: () => rootRouteImport,
} as any)
const AppReservationsRoute = AppReservationsRouteImport.update({
  id: '/app_/reservations',
  path: '/app/reservations',
  getParentRoute: () => rootRouteImport,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/app_/reports',
  path: '/app/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/app_/orders',
  path: '/app/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMenuRoute = AppMenuRouteImport.update({
  id: '/app_/menu',
  path: '/app/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMarketingRoute = AppMarketingRouteImport.update({
  id: '/app_/marketing',
  path: '/app/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLoyaltyRoute = AppLoyaltyRouteImport.update({
  id: '/app_/loyalty',
  path: '/app/loyalty',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHostRoute = AppHostRouteImport.update({
  id: '/app_/host',
  path: '/app/host',
  getParentRoute: () => rootRouteImport,
} as any)
const AppGuestsRoute = AppGuestsRouteImport.update({
  id: '/app_/guests',
  path: '/app/guests',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/app_/dashboard',
  path: '/app/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/app_/analytics',
  path: '/app/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AppGuestsIdRoute = AppGuestsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppGuestsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/app': typeof AppRoute
  '/book': typeof BookRoute
  '/bookings': typeof BookingsRoute
  '/calendar': typeof CalendarRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/floorplan': typeof FloorplanRoute
  '/health': typeof HealthRoute
  '/host-stand': typeof HostStandRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/staff': typeof StaffRoute
  '/start': typeof StartRoute
  '/super-admin-login': typeof SuperAdminLoginRoute
  '/terms': typeof TermsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/guests': typeof AppGuestsRouteWithChildren
  '/app/host': typeof AppHostRoute
  '/app/loyalty': typeof AppLoyaltyRoute
  '/app/marketing': typeof AppMarketingRoute
  '/app/menu': typeof AppMenuRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/reports': typeof AppReportsRoute
  '/app/reservations': typeof AppReservationsRoute
  '/app/server': typeof AppServerRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/billing/checkout': typeof BillingCheckoutRoute
  '/billing/locked': typeof BillingLockedRoute
  '/billing/setup': typeof BillingSetupRoute
  '/book/$slug': typeof BookSlugRoute
  '/customers/$id': typeof CustomersIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/onboarding/$step': typeof OnboardingStepRoute
  '/platform/restaurants': typeof PlatformRestaurantsRoute
  '/platform/': typeof PlatformIndexRoute
  '/app/guests/$id': typeof AppGuestsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/app': typeof AppRoute
  '/book': typeof BookRoute
  '/bookings': typeof BookingsRoute
  '/calendar': typeof CalendarRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/floorplan': typeof FloorplanRoute
  '/health': typeof HealthRoute
  '/host-stand': typeof HostStandRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/staff': typeof StaffRoute
  '/start': typeof StartRoute
  '/super-admin-login': typeof SuperAdminLoginRoute
  '/terms': typeof TermsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/guests': typeof AppGuestsRouteWithChildren
  '/app/host': typeof AppHostRoute
  '/app/loyalty': typeof AppLoyaltyRoute
  '/app/marketing': typeof AppMarketingRoute
  '/app/menu': typeof AppMenuRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/reports': typeof AppReportsRoute
  '/app/reservations': typeof AppReservationsRoute
  '/app/server': typeof AppServerRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/billing/checkout': typeof BillingCheckoutRoute
  '/billing/locked': typeof BillingLockedRoute
  '/billing/setup': typeof BillingSetupRoute
  '/book/$slug': typeof BookSlugRoute
  '/customers/$id': typeof CustomersIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/onboarding/$step': typeof OnboardingStepRoute
  '/platform/restaurants': typeof PlatformRestaurantsRoute
  '/platform': typeof PlatformIndexRoute
  '/app/guests/$id': typeof AppGuestsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/app': typeof AppRoute
  '/book': typeof BookRoute
  '/bookings': typeof BookingsRoute
  '/calendar': typeof CalendarRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/floorplan': typeof FloorplanRoute
  '/health': typeof HealthRoute
  '/host-stand': typeof HostStandRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/staff': typeof StaffRoute
  '/start': typeof StartRoute
  '/super-admin-login': typeof SuperAdminLoginRoute
  '/terms': typeof TermsRoute
  '/app_/analytics': typeof AppAnalyticsRoute
  '/app_/dashboard': typeof AppDashboardRoute
  '/app_/guests': typeof AppGuestsRouteWithChildren
  '/app_/host': typeof AppHostRoute
  '/app_/loyalty': typeof AppLoyaltyRoute
  '/app_/marketing': typeof AppMarketingRoute
  '/app_/menu': typeof AppMenuRoute
  '/app_/orders': typeof AppOrdersRoute
  '/app_/reports': typeof AppReportsRoute
  '/app_/reservations': typeof AppReservationsRoute
  '/app_/server': typeof AppServerRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/billing/checkout': typeof BillingCheckoutRoute
  '/billing/locked': typeof BillingLockedRoute
  '/billing/setup': typeof BillingSetupRoute
  '/book_/$slug': typeof BookSlugRoute
  '/customers_/$id': typeof CustomersIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/onboarding_/$step': typeof OnboardingStepRoute
  '/platform/restaurants': typeof PlatformRestaurantsRoute
  '/platform/': typeof PlatformIndexRoute
  '/app_/guests/$id': typeof AppGuestsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-login'
    | '/app'
    | '/book'
    | '/bookings'
    | '/calendar'
    | '/customers'
    | '/dashboard'
    | '/demo'
    | '/floorplan'
    | '/health'
    | '/host-stand'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/reports'
    | '/settings'
    | '/signup'
    | '/staff'
    | '/start'
    | '/super-admin-login'
    | '/terms'
    | '/app/analytics'
    | '/app/dashboard'
    | '/app/guests'
    | '/app/host'
    | '/app/loyalty'
    | '/app/marketing'
    | '/app/menu'
    | '/app/orders'
    | '/app/reports'
    | '/app/reservations'
    | '/app/server'
    | '/auth/callback'
    | '/billing/checkout'
    | '/billing/locked'
    | '/billing/setup'
    | '/book/$slug'
    | '/customers/$id'
    | '/invite/$token'
    | '/onboarding/$step'
    | '/platform/restaurants'
    | '/platform/'
    | '/app/guests/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-login'
    | '/app'
    | '/book'
    | '/bookings'
    | '/calendar'
    | '/customers'
    | '/dashboard'
    | '/demo'
    | '/floorplan'
    | '/health'
    | '/host-stand'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/reports'
    | '/settings'
    | '/signup'
    | '/staff'
    | '/start'
    | '/super-admin-login'
    | '/terms'
    | '/app/analytics'
    | '/app/dashboard'
    | '/app/guests'
    | '/app/host'
    | '/app/loyalty'
    | '/app/marketing'
    | '/app/menu'
    | '/app/orders'
    | '/app/reports'
    | '/app/reservations'
    | '/app/server'
    | '/auth/callback'
    | '/billing/checkout'
    | '/billing/locked'
    | '/billing/setup'
    | '/book/$slug'
    | '/customers/$id'
    | '/invite/$token'
    | '/onboarding/$step'
    | '/platform/restaurants'
    | '/platform'
    | '/app/guests/$id'
  id:
    | '__root__'
    | '/'
    | '/admin-login'
    | '/app'
    | '/book'
    | '/bookings'
    | '/calendar'
    | '/customers'
    | '/dashboard'
    | '/demo'
    | '/floorplan'
    | '/health'
    | '/host-stand'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/reports'
    | '/settings'
    | '/signup'
    | '/staff'
    | '/start'
    | '/super-admin-login'
    | '/terms'
    | '/app_/analytics'
    | '/app_/dashboard'
    | '/app_/guests'
    | '/app_/host'
    | '/app_/loyalty'
    | '/app_/marketing'
    | '/app_/menu'
    | '/app_/orders'
    | '/app_/reports'
    | '/app_/reservations'
    | '/app_/server'
    | '/auth/callback'
    | '/billing/checkout'
    | '/billing/locked'
    | '/billing/setup'
    | '/book_/$slug'
    | '/customers_/$id'
    | '/invite/$token'
    | '/onboarding_/$step'
    | '/platform/restaurants'
    | '/platform/'
    | '/app_/guests/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AppRoute: typeof AppRoute
  BookRoute: typeof BookRoute
  BookingsRoute: typeof BookingsRoute
  CalendarRoute: typeof CalendarRoute
  CustomersRoute: typeof CustomersRoute
  DashboardRoute: typeof DashboardRoute
  DemoRoute: typeof DemoRoute
  FloorplanRoute: typeof FloorplanRoute
  HealthRoute: typeof HealthRoute
  HostStandRoute: typeof HostStandRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  StaffRoute: typeof StaffRoute
  StartRoute: typeof StartRoute
  SuperAdminLoginRoute: typeof SuperAdminLoginRoute
  TermsRoute: typeof TermsRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppGuestsRoute: typeof AppGuestsRouteWithChildren
  AppHostRoute: typeof AppHostRoute
  AppLoyaltyRoute: typeof AppLoyaltyRoute
  AppMarketingRoute: typeof AppMarketingRoute
  AppMenuRoute: typeof AppMenuRoute
  AppOrdersRoute: typeof AppOrdersRoute
  AppReportsRoute: typeof AppReportsRoute
  AppReservationsRoute: typeof AppReservationsRoute
  AppServerRoute: typeof AppServerRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  BillingCheckoutRoute: typeof BillingCheckoutRoute
  BillingLockedRoute: typeof BillingLockedRoute
  BillingSetupRoute: typeof BillingSetupRoute
  BookSlugRoute: typeof BookSlugRoute
  CustomersIdRoute: typeof CustomersIdRoute
  InviteTokenRoute: typeof InviteTokenRoute
  OnboardingStepRoute: typeof OnboardingStepRoute
  PlatformRestaurantsRoute: typeof PlatformRestaurantsRoute
  PlatformIndexRoute: typeof PlatformIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin-login': {
      id: '/super-admin-login'
      path: '/super-admin-login'
      fullPath: '/super-admin-login'
      preLoaderRoute: typeof SuperAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host-stand': {
      id: '/host-stand'
      path: '/host-stand'
      fullPath: '/host-stand'
      preLoaderRoute: typeof HostStandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/floorplan': {
      id: '/floorplan'
      path: '/floorplan'
      fullPath: '/floorplan'
      preLoaderRoute: typeof FloorplanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/': {
      id: '/platform/'
      path: '/platform'
      fullPath: '/platform/'
      preLoaderRoute: typeof PlatformIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/restaurants': {
      id: '/platform/restaurants'
      path: '/platform/restaurants'
      fullPath: '/platform/restaurants'
      preLoaderRoute: typeof PlatformRestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding_/$step': {
      id: '/onboarding_/$step'
      path: '/onboarding/$step'
      fullPath: '/onboarding/$step'
      preLoaderRoute: typeof OnboardingStepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers_/$id': {
      id: '/customers_/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof CustomersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book_/$slug': {
      id: '/book_/$slug'
      path: '/book/$slug'
      fullPath: '/book/$slug'
      preLoaderRoute: typeof BookSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/setup': {
      id: '/billing/setup'
      path: '/billing/setup'
      fullPath: '/billing/setup'
      preLoaderRoute: typeof BillingSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/locked': {
      id: '/billing/locked'
      path: '/billing/locked'
      fullPath: '/billing/locked'
      preLoaderRoute: typeof BillingLockedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/checkout': {
      id: '/billing/checkout'
      path: '/billing/checkout'
      fullPath: '/billing/checkout'
      preLoaderRoute: typeof BillingCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app_/server': {
      id: '/app_/server'
      path: '/app/server'
      fullPath: '/app/server'
      preLoaderRoute: typeof AppServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app_/reservations': {
      id: '/app_/reservations'
      path: '/app/reservations'
      fullPath: '/app/reservations'
      preLoaderRoute: typeof AppReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app_/reports': {
      id: '/app_/reports'
      path: '/app/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app_/orders': {
      id: '/app_/orders'
      path: '/app/orders'
      fullPath: '/app/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app_/menu': {
      id: '/app_/menu'
      path: '/app/menu'
      fullPath: '/app/menu'
      preLoaderRoute: typeof AppMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app_/marketing': {
      id: '/app_/marketing'
      path: '/app/marketing'
      fullPath: '/app/marketing'
      preLoaderRoute: typeof AppMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app_/loyalty': {
      id: '/app_/loyalty'
      path: '/app/loyalty'
      fullPath: '/app/loyalty'
      preLoaderRoute: typeof AppLoyaltyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app_/host': {
      id: '/app_/host'
      path: '/app/host'
      fullPath: '/app/host'
      preLoaderRoute: typeof AppHostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app_/guests': {
      id: '/app_/guests'
      path: '/app/guests'
      fullPath: '/app/guests'
      preLoaderRoute: typeof AppGuestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app_/dashboard': {
      id: '/app_/dashboard'
      path: '/app/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app_/analytics': {
      id: '/app_/analytics'
      path: '/app/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app_/guests/$id': {
      id: '/app_/guests/$id'
      path: '/$id'
      fullPath: '/app/guests/$id'
      preLoaderRoute: typeof AppGuestsIdRouteImport
      parentRoute: typeof AppGuestsRoute
    }
  }
}

interface AppGuestsRouteChildren {
  AppGuestsIdRoute: typeof AppGuestsIdRoute
}

const AppGuestsRouteChildren: AppGuestsRouteChildren = {
  AppGuestsIdRoute: AppGuestsIdRoute,
}

const AppGuestsRouteWithChildren = AppGuestsRoute._addFileChildren(
  AppGuestsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminLoginRoute: AdminLoginRoute,
  AppRoute: AppRoute,
  BookRoute: BookRoute,
  BookingsRoute: BookingsRoute,
  CalendarRoute: CalendarRoute,
  CustomersRoute: CustomersRoute,
  DashboardRoute: DashboardRoute,
  DemoRoute: DemoRoute,
  FloorplanRoute: FloorplanRoute,
  HealthRoute: HealthRoute,
  HostStandRoute: HostStandRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  StaffRoute: StaffRoute,
  StartRoute: StartRoute,
  SuperAdminLoginRoute: SuperAdminLoginRoute,
  TermsRoute: TermsRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppGuestsRoute: AppGuestsRouteWithChildren,
  AppHostRoute: AppHostRoute,
  AppLoyaltyRoute: AppLoyaltyRoute,
  AppMarketingRoute: AppMarketingRoute,
  AppMenuRoute: AppMenuRoute,
  AppOrdersRoute: AppOrdersRoute,
  AppReportsRoute: AppReportsRoute,
  AppReservationsRoute: AppReservationsRoute,
  AppServerRoute: AppServerRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  BillingCheckoutRoute: BillingCheckoutRoute,
  BillingLockedRoute: BillingLockedRoute,
  BillingSetupRoute: BillingSetupRoute,
  BookSlugRoute: BookSlugRoute,
  CustomersIdRoute: CustomersIdRoute,
  InviteTokenRoute: InviteTokenRoute,
  OnboardingStepRoute: OnboardingStepRoute,
  PlatformRestaurantsRoute: PlatformRestaurantsRoute,
  PlatformIndexRoute: PlatformIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
