/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ServerLoginRouteImport } from './routes/server-login'
import { Route as ServerAppRouteImport } from './routes/server-app'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProductAnalyticsRouteImport } from './routes/product-analytics'
import { Route as PitchdeckRouteImport } from './routes/pitchdeck'
import { Route as PayrollRouteImport } from './routes/payroll'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as MarketingRouteImport } from './routes/marketing'
import { Route as LoyaltyRouteImport } from './routes/loyalty'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as HostStandRouteImport } from './routes/host-stand'
import { Route as FloorplanRouteImport } from './routes/floorplan'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as BookRouteImport } from './routes/book'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarketingSmsRouteImport } from './routes/marketing.sms'
import { Route as MarketingReviewsRouteImport } from './routes/marketing.reviews'
import { Route as MarketingReferralRouteImport } from './routes/marketing.referral'
import { Route as MarketingPromotionsRouteImport } from './routes/marketing.promotions'
import { Route as MarketingLandingRouteImport } from './routes/marketing.landing'
import { Route as MarketingEmailRouteImport } from './routes/marketing.email'
import { Route as MarketingCreatorsRouteImport } from './routes/marketing.creators'
import { Route as MarketingCatchBackRouteImport } from './routes/marketing.catch-back'
import { Route as CustomersIdRouteImport } from './routes/customers_.$id'
import { Route as BookSlugRouteImport } from './routes/book_.$slug'

const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerLoginRoute = ServerLoginRouteImport.update({
  id: '/server-login',
  path: '/server-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerAppRoute = ServerAppRouteImport.update({
  id: '/server-app',
  path: '/server-app',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductAnalyticsRoute = ProductAnalyticsRouteImport.update({
  id: '/product-analytics',
  path: '/product-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const PitchdeckRoute = PitchdeckRouteImport.update({
  id: '/pitchdeck',
  path: '/pitchdeck',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollRoute = PayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoyaltyRoute = LoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const HostStandRoute = HostStandRouteImport.update({
  id: '/host-stand',
  path: '/host-stand',
  getParentRoute: () => rootRouteImport,
} as any)
const FloorplanRoute = FloorplanRouteImport.update({
  id: '/floorplan',
  path: '/floorplan',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingSmsRoute = MarketingSmsRouteImport.update({
  id: '/sms',
  path: '/sms',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingReviewsRoute = MarketingReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingReferralRoute = MarketingReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingPromotionsRoute = MarketingPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingLandingRoute = MarketingLandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingEmailRoute = MarketingEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingCreatorsRoute = MarketingCreatorsRouteImport.update({
  id: '/creators',
  path: '/creators',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingCatchBackRoute = MarketingCatchBackRouteImport.update({
  id: '/catch-back',
  path: '/catch-back',
  getParentRoute: () => MarketingRoute,
} as any)
const CustomersIdRoute = CustomersIdRouteImport.update({
  id: '/customers_/$id',
  path: '/customers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BookSlugRoute = BookSlugRouteImport.update({
  id: '/book_/$slug',
  path: '/book/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/book': typeof BookRoute
  '/bookings': typeof BookingsRoute
  '/calendar': typeof CalendarRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/floorplan': typeof FloorplanRoute
  '/host-stand': typeof HostStandRoute
  '/integrations': typeof IntegrationsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/loyalty': typeof LoyaltyRoute
  '/marketing': typeof MarketingRouteWithChildren
  '/menu': typeof MenuRoute
  '/onboarding': typeof OnboardingRoute
  '/orders': typeof OrdersRoute
  '/payroll': typeof PayrollRoute
  '/pitchdeck': typeof PitchdeckRoute
  '/product-analytics': typeof ProductAnalyticsRoute
  '/reports': typeof ReportsRoute
  '/server-app': typeof ServerAppRoute
  '/server-login': typeof ServerLoginRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/staff': typeof StaffRoute
  '/book/$slug': typeof BookSlugRoute
  '/customers/$id': typeof CustomersIdRoute
  '/marketing/catch-back': typeof MarketingCatchBackRoute
  '/marketing/creators': typeof MarketingCreatorsRoute
  '/marketing/email': typeof MarketingEmailRoute
  '/marketing/landing': typeof MarketingLandingRoute
  '/marketing/promotions': typeof MarketingPromotionsRoute
  '/marketing/referral': typeof MarketingReferralRoute
  '/marketing/reviews': typeof MarketingReviewsRoute
  '/marketing/sms': typeof MarketingSmsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/book': typeof BookRoute
  '/bookings': typeof BookingsRoute
  '/calendar': typeof CalendarRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/floorplan': typeof FloorplanRoute
  '/host-stand': typeof HostStandRoute
  '/integrations': typeof IntegrationsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/loyalty': typeof LoyaltyRoute
  '/marketing': typeof MarketingRouteWithChildren
  '/menu': typeof MenuRoute
  '/onboarding': typeof OnboardingRoute
  '/orders': typeof OrdersRoute
  '/payroll': typeof PayrollRoute
  '/pitchdeck': typeof PitchdeckRoute
  '/product-analytics': typeof ProductAnalyticsRoute
  '/reports': typeof ReportsRoute
  '/server-app': typeof ServerAppRoute
  '/server-login': typeof ServerLoginRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/staff': typeof StaffRoute
  '/book/$slug': typeof BookSlugRoute
  '/customers/$id': typeof CustomersIdRoute
  '/marketing/catch-back': typeof MarketingCatchBackRoute
  '/marketing/creators': typeof MarketingCreatorsRoute
  '/marketing/email': typeof MarketingEmailRoute
  '/marketing/landing': typeof MarketingLandingRoute
  '/marketing/promotions': typeof MarketingPromotionsRoute
  '/marketing/referral': typeof MarketingReferralRoute
  '/marketing/reviews': typeof MarketingReviewsRoute
  '/marketing/sms': typeof MarketingSmsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/book': typeof BookRoute
  '/bookings': typeof BookingsRoute
  '/calendar': typeof CalendarRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/floorplan': typeof FloorplanRoute
  '/host-stand': typeof HostStandRoute
  '/integrations': typeof IntegrationsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/loyalty': typeof LoyaltyRoute
  '/marketing': typeof MarketingRouteWithChildren
  '/menu': typeof MenuRoute
  '/onboarding': typeof OnboardingRoute
  '/orders': typeof OrdersRoute
  '/payroll': typeof PayrollRoute
  '/pitchdeck': typeof PitchdeckRoute
  '/product-analytics': typeof ProductAnalyticsRoute
  '/reports': typeof ReportsRoute
  '/server-app': typeof ServerAppRoute
  '/server-login': typeof ServerLoginRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/staff': typeof StaffRoute
  '/book_/$slug': typeof BookSlugRoute
  '/customers_/$id': typeof CustomersIdRoute
  '/marketing/catch-back': typeof MarketingCatchBackRoute
  '/marketing/creators': typeof MarketingCreatorsRoute
  '/marketing/email': typeof MarketingEmailRoute
  '/marketing/landing': typeof MarketingLandingRoute
  '/marketing/promotions': typeof MarketingPromotionsRoute
  '/marketing/referral': typeof MarketingReferralRoute
  '/marketing/reviews': typeof MarketingReviewsRoute
  '/marketing/sms': typeof MarketingSmsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-login'
    | '/book'
    | '/bookings'
    | '/calendar'
    | '/customers'
    | '/dashboard'
    | '/floorplan'
    | '/host-stand'
    | '/integrations'
    | '/leaderboard'
    | '/login'
    | '/loyalty'
    | '/marketing'
    | '/menu'
    | '/onboarding'
    | '/orders'
    | '/payroll'
    | '/pitchdeck'
    | '/product-analytics'
    | '/reports'
    | '/server-app'
    | '/server-login'
    | '/settings'
    | '/signup'
    | '/staff'
    | '/book/$slug'
    | '/customers/$id'
    | '/marketing/catch-back'
    | '/marketing/creators'
    | '/marketing/email'
    | '/marketing/landing'
    | '/marketing/promotions'
    | '/marketing/referral'
    | '/marketing/reviews'
    | '/marketing/sms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-login'
    | '/book'
    | '/bookings'
    | '/calendar'
    | '/customers'
    | '/dashboard'
    | '/floorplan'
    | '/host-stand'
    | '/integrations'
    | '/leaderboard'
    | '/login'
    | '/loyalty'
    | '/marketing'
    | '/menu'
    | '/onboarding'
    | '/orders'
    | '/payroll'
    | '/pitchdeck'
    | '/product-analytics'
    | '/reports'
    | '/server-app'
    | '/server-login'
    | '/settings'
    | '/signup'
    | '/staff'
    | '/book/$slug'
    | '/customers/$id'
    | '/marketing/catch-back'
    | '/marketing/creators'
    | '/marketing/email'
    | '/marketing/landing'
    | '/marketing/promotions'
    | '/marketing/referral'
    | '/marketing/reviews'
    | '/marketing/sms'
  id:
    | '__root__'
    | '/'
    | '/admin-login'
    | '/book'
    | '/bookings'
    | '/calendar'
    | '/customers'
    | '/dashboard'
    | '/floorplan'
    | '/host-stand'
    | '/integrations'
    | '/leaderboard'
    | '/login'
    | '/loyalty'
    | '/marketing'
    | '/menu'
    | '/onboarding'
    | '/orders'
    | '/payroll'
    | '/pitchdeck'
    | '/product-analytics'
    | '/reports'
    | '/server-app'
    | '/server-login'
    | '/settings'
    | '/signup'
    | '/staff'
    | '/book_/$slug'
    | '/customers_/$id'
    | '/marketing/catch-back'
    | '/marketing/creators'
    | '/marketing/email'
    | '/marketing/landing'
    | '/marketing/promotions'
    | '/marketing/referral'
    | '/marketing/reviews'
    | '/marketing/sms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminLoginRoute: typeof AdminLoginRoute
  BookRoute: typeof BookRoute
  BookingsRoute: typeof BookingsRoute
  CalendarRoute: typeof CalendarRoute
  CustomersRoute: typeof CustomersRoute
  DashboardRoute: typeof DashboardRoute
  FloorplanRoute: typeof FloorplanRoute
  HostStandRoute: typeof HostStandRoute
  IntegrationsRoute: typeof IntegrationsRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  LoyaltyRoute: typeof LoyaltyRoute
  MarketingRoute: typeof MarketingRouteWithChildren
  MenuRoute: typeof MenuRoute
  OnboardingRoute: typeof OnboardingRoute
  OrdersRoute: typeof OrdersRoute
  PayrollRoute: typeof PayrollRoute
  PitchdeckRoute: typeof PitchdeckRoute
  ProductAnalyticsRoute: typeof ProductAnalyticsRoute
  ReportsRoute: typeof ReportsRoute
  ServerAppRoute: typeof ServerAppRoute
  ServerLoginRoute: typeof ServerLoginRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  StaffRoute: typeof StaffRoute
  BookSlugRoute: typeof BookSlugRoute
  CustomersIdRoute: typeof CustomersIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/server-login': {
      id: '/server-login'
      path: '/server-login'
      fullPath: '/server-login'
      preLoaderRoute: typeof ServerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/server-app': {
      id: '/server-app'
      path: '/server-app'
      fullPath: '/server-app'
      preLoaderRoute: typeof ServerAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product-analytics': {
      id: '/product-analytics'
      path: '/product-analytics'
      fullPath: '/product-analytics'
      preLoaderRoute: typeof ProductAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pitchdeck': {
      id: '/pitchdeck'
      path: '/pitchdeck'
      fullPath: '/pitchdeck'
      preLoaderRoute: typeof PitchdeckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll': {
      id: '/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof PayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing': {
      id: '/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loyalty': {
      id: '/loyalty'
      path: '/loyalty'
      fullPath: '/loyalty'
      preLoaderRoute: typeof LoyaltyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host-stand': {
      id: '/host-stand'
      path: '/host-stand'
      fullPath: '/host-stand'
      preLoaderRoute: typeof HostStandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/floorplan': {
      id: '/floorplan'
      path: '/floorplan'
      fullPath: '/floorplan'
      preLoaderRoute: typeof FloorplanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/sms': {
      id: '/marketing/sms'
      path: '/sms'
      fullPath: '/marketing/sms'
      preLoaderRoute: typeof MarketingSmsRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/marketing/reviews': {
      id: '/marketing/reviews'
      path: '/reviews'
      fullPath: '/marketing/reviews'
      preLoaderRoute: typeof MarketingReviewsRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/marketing/referral': {
      id: '/marketing/referral'
      path: '/referral'
      fullPath: '/marketing/referral'
      preLoaderRoute: typeof MarketingReferralRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/marketing/promotions': {
      id: '/marketing/promotions'
      path: '/promotions'
      fullPath: '/marketing/promotions'
      preLoaderRoute: typeof MarketingPromotionsRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/marketing/landing': {
      id: '/marketing/landing'
      path: '/landing'
      fullPath: '/marketing/landing'
      preLoaderRoute: typeof MarketingLandingRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/marketing/email': {
      id: '/marketing/email'
      path: '/email'
      fullPath: '/marketing/email'
      preLoaderRoute: typeof MarketingEmailRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/marketing/creators': {
      id: '/marketing/creators'
      path: '/creators'
      fullPath: '/marketing/creators'
      preLoaderRoute: typeof MarketingCreatorsRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/marketing/catch-back': {
      id: '/marketing/catch-back'
      path: '/catch-back'
      fullPath: '/marketing/catch-back'
      preLoaderRoute: typeof MarketingCatchBackRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/customers_/$id': {
      id: '/customers_/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof CustomersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book_/$slug': {
      id: '/book_/$slug'
      path: '/book/$slug'
      fullPath: '/book/$slug'
      preLoaderRoute: typeof BookSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MarketingRouteChildren {
  MarketingCatchBackRoute: typeof MarketingCatchBackRoute
  MarketingCreatorsRoute: typeof MarketingCreatorsRoute
  MarketingEmailRoute: typeof MarketingEmailRoute
  MarketingLandingRoute: typeof MarketingLandingRoute
  MarketingPromotionsRoute: typeof MarketingPromotionsRoute
  MarketingReferralRoute: typeof MarketingReferralRoute
  MarketingReviewsRoute: typeof MarketingReviewsRoute
  MarketingSmsRoute: typeof MarketingSmsRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingCatchBackRoute: MarketingCatchBackRoute,
  MarketingCreatorsRoute: MarketingCreatorsRoute,
  MarketingEmailRoute: MarketingEmailRoute,
  MarketingLandingRoute: MarketingLandingRoute,
  MarketingPromotionsRoute: MarketingPromotionsRoute,
  MarketingReferralRoute: MarketingReferralRoute,
  MarketingReviewsRoute: MarketingReviewsRoute,
  MarketingSmsRoute: MarketingSmsRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminLoginRoute: AdminLoginRoute,
  BookRoute: BookRoute,
  BookingsRoute: BookingsRoute,
  CalendarRoute: CalendarRoute,
  CustomersRoute: CustomersRoute,
  DashboardRoute: DashboardRoute,
  FloorplanRoute: FloorplanRoute,
  HostStandRoute: HostStandRoute,
  IntegrationsRoute: IntegrationsRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  LoyaltyRoute: LoyaltyRoute,
  MarketingRoute: MarketingRouteWithChildren,
  MenuRoute: MenuRoute,
  OnboardingRoute: OnboardingRoute,
  OrdersRoute: OrdersRoute,
  PayrollRoute: PayrollRoute,
  PitchdeckRoute: PitchdeckRoute,
  ProductAnalyticsRoute: ProductAnalyticsRoute,
  ReportsRoute: ReportsRoute,
  ServerAppRoute: ServerAppRoute,
  ServerLoginRoute: ServerLoginRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  StaffRoute: StaffRoute,
  BookSlugRoute: BookSlugRoute,
  CustomersIdRoute: CustomersIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
